// Mock de jogos (adicione a propriedade platforms)
export const GAMES = [
  {
    id: 1,
    name: "The Witcher 3",
    cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r6b.jpg",
    genre: "RPG",
    year: 2015,
    rating: 4.9,
    description: "Aventura épica em mundo aberto com Geralt de Rívia.",
    platforms: ["pc", "xbox", "playstation", "notebook"],
    isNew: false,
  },
  {
    id: 2,
    name: "Hollow Knight",
    cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1tmu.jpg",
    genre: "Metroidvania",
    year: 2017,
    rating: 4.8,
    description: "Explore Hallownest em um dos melhores indies já feitos.",
    platforms: ["pc", "switch", "xbox", "playstation", "notebook"],
    isNew: false,
  },
  {
    id: 3,
    name: "Cyberpunk 2077",
    cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r6e.jpg",
    genre: "RPG",
    year: 2020,
    rating: 4.2,
    description: "Futuro distópico, ação e escolhas em Night City.",
    platforms: ["pc", "xbox", "playstation", "notebook"],
    isNew: false,
  },
  {
    id: 4,
    name: "God of War",
    cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1t3v.jpg",
    genre: "Ação",
    year: 2018,
    rating: 4.7,
    description: "Kratos e Atreus em uma jornada épica pela mitologia nórdica.",
    platforms: ["playstation", "pc"],
    isNew: false,
  },
  {
    id: 5,
    name: "Stardew Valley",
    cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.jpg",
    genre: "Simulação",
    year: 2016,
    rating: 4.6,
    description: "Cultive, socialize e explore em um charmoso mundo pixelado.",
    platforms: ["pc", "switch", "xbox", "playstation", "mobile", "notebook"],
    isNew: false,
  },
  {
    id: 6,
    name: "Celeste",
    cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.jpg",
    genre: "Plataforma",
    year: 2018,
    rating: 4.8,
    description: "Supere desafios e descubra uma história emocionante.",
    platforms: ["pc", "switch", "xbox", "playstation", "notebook"],
    isNew: false,
  },
  {
    id: 7,
    name: "Elden Ring",
    cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4q9b.jpg",
    genre: "RPG",
    year: 2022,
    rating: 4.9,
    description:
      "Explore as Terras Intermédias em um novo épico da FromSoftware.",
    platforms: ["pc", "xbox", "playstation"],
    isNew: true,
  },
  {
    id: 8,
    name: "Hi-Fi Rush",
    cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6w7c.jpg",
    genre: "Ação",
    year: 2023,
    rating: 4.5,
    description: "Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.Ritmo e ação em um dos lançamentos mais recentes.",
    platforms: ["pc", "xbox"],
    isNew: true,
  },
];

// Gêneros únicos extraídos dos jogos
export const GENRES = [...new Set(GAMES.map((g) => g.genre))];
